name: Kbot workflow

on:
  push:
    branches:
      - 'develop'

jobs:
  ci:
    name: Kbot CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        env:
          TELE_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: make test

      - name: Build
        run: make image

      - name: Registry login
        uses: actions/checkout@v4
        permissions:
          packages: write
          contents: read

      - name: Publish service
        run: echo "${{ secrets.GITHUB_TOKEN }}" | 
          docker login ghcr.io -u $ --password-stdin |
          make push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: echo "VERSION=$(shell git describe --tags --abbrev=0)-$(shell git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: mikefarah/yq@master
        with:
          cmd: yq i '.image.tag=strenv(VERSION)' helm/values.yaml

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "update version $VERSION"
          git push